# Generated by Django 3.1.6 on 2021-03-20 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210320_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.transaction')),
                ('status', models.BooleanField(default=True)),
            ],
            bases=('dashboard.transaction',),
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.transaction')),
                ('status', models.BooleanField(default=True)),
            ],
            bases=('dashboard.transaction',),
        ),
    ]
