# Generated by Django 3.1.6 on 2021-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_borrow_lend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lend',
            name='transaction_ptr',
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
        migrations.DeleteModel(
            name='Lend',
        ),
    ]
