# Generated by Django 3.1.6 on 2021-03-24 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210320_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
